stages:
  - build
  - docker

variables:
  CONTAINER_IMAGE: registry.gitlab.com/oddwes/resume:latest

prod_build:
  image: node:14.16.0-alpine3.10
  stage: build
  script:
    - NODE_ENV=production
    - yarn install --frozen-lockfile --check-files
    - yarn build
  # only:
  #   - tags
  artifacts:
    paths:
      - build/

docker_image_build_release:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: docker
  # only:
  #   - tags
  script:
    - echo *
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
