stages:
  - docker_build
  - deploy

services:
  - docker:20.10.8-dind

variables:
  DOCKER_DRIVER: overlay2
  BUILDX_VERSION: "v0.6.1"
  BUILDX_ARCH: "linux-amd64"
  KUBECONFIG:  /root/.kube/config

build_images:
  image: docker:20.10.8
  stage: docker_build
  only:
    - tags
  environment:
    name: production
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username
      $CI_REGISTRY_USER --password-stdin
    - wget -O /usr/bin/docker-buildx
      https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.${BUILDX_ARCH}
    - chmod +x /usr/bin/docker-buildx
    - docker info
  script:
    - docker-buildx create --use
    - docker-buildx build --platform linux/arm,linux/amd64 -t $CI_REGISTRY_IMAGE:latest --push .

deploy:
  image: dtzar/helm-kubectl
  stage: deploy
  only:
      - tags
  environment:
    name: production
  before_script:
      - sed -ie "s/deploy-date-value/$(date)/g" kubernetes/pipeline_deployment.yaml
      - mkdir -p /root/.kube/ && touch /root/.kube/config
      - echo ${KUBERNETES_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
      - kubectl apply -f kubernetes/pipeline_deployment.yaml


