stages:
  - build_docker
  - deploy

variables:
  KUBECONFIG:  /root/.kube/config

image_build_release:
  image: jdrouet/docker-with-buildx:stable
  stage: build_docker
  only:
    - tags
  services:
    - docker:dind
  before-script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker buildx create --use
    - docker buildx build  --push --platform linux/arm64,linux/amd64 -t registry.gitlab.com/oddwes-main/resume:latest -t registry.gitlab.com/oddwes-main/resume:latest .

# deploy:
#   image: dtzar/helm-kubectl
#   stage: deploy
#   only:
#       - tags
#   environment:
#     name: production
#   before_script:
#       - sed -ie "s/deploy-date-value/$(date)/g" kubernetes/pipeline_deployment.yaml
#       - mkdir -p /root/.kube/ && touch /root/.kube/config
#       - echo ${KUBERNETES_KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
#   script:
#       - kubectl apply -f kubernetes/pipeline_deployment.yaml