apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  namespace: public
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-public-resume
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resume
      annotations:
        deploy-date: "deploy-date-value"