---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-workload
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resume-workload
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: resume-workload
        image: registry.gitlab.com/oddwes-main/resume
        ports:
        - containerPort: 80
          hostPort: 8080
      imagePullSecrets:
      - name: gitlab-auth