---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
  namespace: public
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-workload
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: resume-workload
    spec:
      containers:
      - name: resume-workload
        image: registry.gitlab.com/oddwes-main/resume
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: resume-workload
  namespace: public
spec:
  selector:
    app: resume-workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: resume-ingress
  namespace: public
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`resume.oddwes.ca`)
    kind: Rule
    services:
    - name: resume-workload
      port: 80
  tls:
    certResolver: letsencrypt
